### ISSUE TITLE
cannot extract keys with dots in their names

### ISSUE THREAD

**Issue by yoshikakbudto** [JetBrains/teamcity-hashicorp-vault-plugin#22]
Using vault 1.1.3

Having a **K/V 2** keys  configured in TeamCity properties as:
prop1:  %vault:kv/data/creds!/user1%
prop2:  %vault:kv/data/creds!/vasya.p%

The value of prop1 extracts OK
The value of prop2 (wich contains dot in its key) doesnt. The build fails with WARN? (shouldnt it be at least ERROR severity?):

```
[2019-07-04 10:54:24,915]   WARN - .agent.VaultParametersResolver - Cannot extract 'vasya.p' data from '/kv/data/creds', full reference: /kv/data/creds!/vasya.p
com.jayway.jsonpath.PathNotFoundException: Missing property in path $['vasya']
        at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:72)
        at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:79)
        at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
        at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
        at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:157)
        at org.jetbrains.teamcity.vault.agent.VaultParametersResolver$VaultParametersFetcher.extract(VaultParametersResolver.kt:161)
        at org.jetbrains.teamcity.vault.agent.VaultParametersResolver$VaultParametersFetcher.getReplacements(VaultParametersResolver.kt:117)
        at org.jetbrains.teamcity.vault.agent.VaultParametersResolver$VaultParametersFetcher.doFetchAndPrepareReplacements(VaultParametersResolver.kt:84)
        at org.jetbrains.teamcity.vault.agent.VaultParametersResolver.doFetchAndPrepareReplacements(VaultParametersResolver.kt:74)
        at org.jetbrains.teamcity.vault.agent.VaultParametersResolver.doFetchAndPrepareReplacements(VaultParametersResolver.kt:70)
        at org.jetbrains.teamcity.vault.agent.VaultParametersResolver.resolve(VaultParametersResolver.kt:51)
        at org.jetbrains.teamcity.vault.agent.VaultBuildFeature$buildStarted$$inlined$forEach$lambda$1.invoke(VaultBuildFeature.kt:136)
        at org.jetbrains.teamcity.vault.agent.VaultBuildFeature$buildStarted$$inlined$forEach$lambda$1.invoke(VaultBuildFeature.kt:33)
        at org.jetbrains.teamcity.vault.UtilKt.activity(util.kt:155)
        at org.jetbrains.teamcity.vault.agent.VaultBuildFeature.buildStarted(VaultBuildFeature.kt:79)
        at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:128)
        at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
        at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:122)
        at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:72)
        at com.sun.proxy.$Proxy7.buildStarted(Unknown Source)
        at jetbrains.buildServer.agent.impl.buildStages.startStages.FireBuildStartedStage.doBuildState(FireBuildStartedStage.java:20)
        at jetbrains.buildServer.agent.impl.buildStages.startStages.FireEventStageBase.doBuildStage(FireEventStageBase.java:26)
        at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
        at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
        at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
        at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
        at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
        at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:79)
        at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:309)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:54)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:272)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by vpolozov** [comment]
Looking into code one can find, that JsonPath is used to get the attribute value in Json from the Vault.
Thus, the correct way to reference attributes with dots is: `%vault:kv/data/creds!/$.['vasya.p']%`
