### ISSUE TITLE
TeamCity Enterprise 2021.1 (build 92597)

### ISSUE THREAD

**Issue by vpolozov** [JetBrains/teamcity-hashicorp-vault-plugin#43]
After upgrade to TeamCity Enterprise 2021.1 (build 92597) plugin stopped working:

> Failed to fetch HashiCorp Vault wrapped token: com.fasterxml.jackson.datatype.jdk8.Jdk8Module cannot be cast to com.fasterxml.jackson.databind.Module: java.lang.ClassCastException: com.fasterxml.jackson.datatype.jdk8.Jdk8Module cannot be cast to com.fasterxml.jackson.databind.Module, see teamcity-server.log for details

teamcity-server.log:

> [2021-06-01 10:07:30,581]   WARN - aultBuildStartContextProcessor - Failed to fetch HashiCorp Vault wrapped token: com.fasterxml.jackson.datatype.jdk8.Jdk8Module cannot be cast to com.fasterxml.jackson.databind.Module
> java.lang.ClassCastException: com.fasterxml.jackson.datatype.jdk8.Jdk8Module cannot be cast to com.fasterxml.jackson.databind.Module
>         at org.jetbrains.teamcity.vault.support.Jackson2ObjectMapperBuilder.registerWellKnownModulesIfAvailable(Jackson2ObjectMapperBuilder.java:140)
>         at org.jetbrains.teamcity.vault.support.Jackson2ObjectMapperBuilder.configure(Jackson2ObjectMapperBuilder.java:85)
>         at org.jetbrains.teamcity.vault.support.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:72)
>         at org.jetbrains.teamcity.vault.support.MappingJackson2HttpMessageConverter.<init>(MappingJackson2HttpMessageConverter.java:50)
>         at org.jetbrains.teamcity.vault.UtilKt.createRestTemplate(util.kt:97)
>         at org.jetbrains.teamcity.vault.UtilKt.createRestTemplate(util.kt:74)
>         at org.jetbrains.teamcity.vault.support.VaultTemplate.createSessionTemplate(VaultTemplate.java:102)
>         at org.jetbrains.teamcity.vault.support.VaultTemplate.<init>(VaultTemplate.java:76)
>         at org.jetbrains.teamcity.vault.server.VaultConnector$Companion.doRequestWrappedToken(VaultConnector.kt:167)
>         at org.jetbrains.teamcity.vault.server.VaultConnector.requestWrappedToken(VaultConnector.kt:239)
>         at org.jetbrains.teamcity.vault.server.VaultBuildStartContextProcessor.updateParameters(VaultBuildStartContextProcessor.kt:88)
>         at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.prepareRunners(RunningBuildImpl.java:202)
>         at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.createAgentBuild(RunningBuildImpl.java:2)
>         at jetbrains.buildServer.serverSide.impl.BuildStarter.startBuildOnAgent(BuildStarter.java:200)
>         at jetbrains.buildServer.serverSide.impl.BuildStarter.afterChangesCollecting(BuildStarter.java:161)
>         at jetbrains.buildServer.serverSide.impl.BuildStarter.waitForChangesCollectingAndContinue(BuildStarter.java:167)
>         at jetbrains.buildServer.serverSide.impl.BuildStarter.lambda$null$0(BuildStarter.java:201)
>         at jetbrains.buildServer.serverSide.impl.BuildStarter.handleBuildStartAction(BuildStarter.java:76)
>         at jetbrains.buildServer.serverSide.impl.BuildStarter.lambda$null$1(BuildStarter.java:117)
>         at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
>         at jetbrains.buildServer.serverSide.impl.BuildStarter.lambda$startBuildAsync$2(BuildStarter.java:317)
>         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> [2021-06-01 10:07:30,612]   INFO -   jetbrains.buildServer.SERVER - Build interrupted (INTERRUPTED_WITH_RERUN) with details: [comment: Failed to fetch HashiCorp Vault wrapped token: com.fasterxml.jackson.datatype.jdk8.Jdk8Module cannot be cast to com.fasterxml.jackson.databind.Module: java.lang.ClassCastException: com.fasterxml.jackson.datatype.jdk8.Jdk8Module cannot be cast to com.fasterxml.jackson.databind.Module, see teamcity-server.log for details]. Build: MedM Backend Images Builder / health_backend builds {id=MedMBackendImagesBuilder_HealthBackendBuilds, internal id=bt3438} #1616 {promotion id=423591, branch=CUSTOMER_LIFE365, agent="server-6" {id=2509}, triggered by "Git" (##vcsName='jetbrains.git' type='vcs' triggerId='vcsTrigger'), canceled=[comment: Failed to fetch HashiCorp Vault wrapped token: com.fasterxml.jackson.datatype.jdk8.Jdk8Module cannot be cast to com.fasterxml.jackson.databind.Module: java.lang.ClassCastException: com.fasterxml.jackson.datatype.jdk8.Jdk8Module cannot be cast to com.fasterxml.jackson.databind.Module, see teamcity-server.log for details]. Started 2021-06-01 10:07:28.162, running}

**Comment by vpolozov** [comment]
Plugins are not automatically updated with TC server. Updating plugin to the latest version (0.1.103) fixed the issue
